# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/maxgm/Downloads/CLion-2021.2.1/clion-2021.2.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/maxgm/Downloads/CLion-2021.2.1/clion-2021.2.1/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maxgm/CLionProjects/RentACar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maxgm/CLionProjects/RentACar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/maxgm/Downloads/CLion-2021.2.1/clion-2021.2.1/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/maxgm/Downloads/CLion-2021.2.1/clion-2021.2.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maxgm/CLionProjects/RentACar/CMakeFiles /home/maxgm/CLionProjects/RentACar//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maxgm/CLionProjects/RentACar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RentACar

# Build rule for target.
RentACar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RentACar
.PHONY : RentACar

# fast build rule for target.
RentACar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/build
.PHONY : RentACar/fast

Backtracking/Graph.o: Backtracking/Graph.cpp.o
.PHONY : Backtracking/Graph.o

# target to build an object file
Backtracking/Graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/Backtracking/Graph.cpp.o
.PHONY : Backtracking/Graph.cpp.o

Backtracking/Graph.i: Backtracking/Graph.cpp.i
.PHONY : Backtracking/Graph.i

# target to preprocess a source file
Backtracking/Graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/Backtracking/Graph.cpp.i
.PHONY : Backtracking/Graph.cpp.i

Backtracking/Graph.s: Backtracking/Graph.cpp.s
.PHONY : Backtracking/Graph.s

# target to generate assembly for a file
Backtracking/Graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/Backtracking/Graph.cpp.s
.PHONY : Backtracking/Graph.cpp.s

Backtracking/Node.o: Backtracking/Node.cpp.o
.PHONY : Backtracking/Node.o

# target to build an object file
Backtracking/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/Backtracking/Node.cpp.o
.PHONY : Backtracking/Node.cpp.o

Backtracking/Node.i: Backtracking/Node.cpp.i
.PHONY : Backtracking/Node.i

# target to preprocess a source file
Backtracking/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/Backtracking/Node.cpp.i
.PHONY : Backtracking/Node.cpp.i

Backtracking/Node.s: Backtracking/Node.cpp.s
.PHONY : Backtracking/Node.s

# target to generate assembly for a file
Backtracking/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/Backtracking/Node.cpp.s
.PHONY : Backtracking/Node.cpp.s

Backtracking/NodeLogistic.o: Backtracking/NodeLogistic.cpp.o
.PHONY : Backtracking/NodeLogistic.o

# target to build an object file
Backtracking/NodeLogistic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/Backtracking/NodeLogistic.cpp.o
.PHONY : Backtracking/NodeLogistic.cpp.o

Backtracking/NodeLogistic.i: Backtracking/NodeLogistic.cpp.i
.PHONY : Backtracking/NodeLogistic.i

# target to preprocess a source file
Backtracking/NodeLogistic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/Backtracking/NodeLogistic.cpp.i
.PHONY : Backtracking/NodeLogistic.cpp.i

Backtracking/NodeLogistic.s: Backtracking/NodeLogistic.cpp.s
.PHONY : Backtracking/NodeLogistic.s

# target to generate assembly for a file
Backtracking/NodeLogistic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/Backtracking/NodeLogistic.cpp.s
.PHONY : Backtracking/NodeLogistic.cpp.s

GUI/ConnectionsGUI.o: GUI/ConnectionsGUI.cpp.o
.PHONY : GUI/ConnectionsGUI.o

# target to build an object file
GUI/ConnectionsGUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/GUI/ConnectionsGUI.cpp.o
.PHONY : GUI/ConnectionsGUI.cpp.o

GUI/ConnectionsGUI.i: GUI/ConnectionsGUI.cpp.i
.PHONY : GUI/ConnectionsGUI.i

# target to preprocess a source file
GUI/ConnectionsGUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/GUI/ConnectionsGUI.cpp.i
.PHONY : GUI/ConnectionsGUI.cpp.i

GUI/ConnectionsGUI.s: GUI/ConnectionsGUI.cpp.s
.PHONY : GUI/ConnectionsGUI.s

# target to generate assembly for a file
GUI/ConnectionsGUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/GUI/ConnectionsGUI.cpp.s
.PHONY : GUI/ConnectionsGUI.cpp.s

GUI/NodeGUI.o: GUI/NodeGUI.cpp.o
.PHONY : GUI/NodeGUI.o

# target to build an object file
GUI/NodeGUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/GUI/NodeGUI.cpp.o
.PHONY : GUI/NodeGUI.cpp.o

GUI/NodeGUI.i: GUI/NodeGUI.cpp.i
.PHONY : GUI/NodeGUI.i

# target to preprocess a source file
GUI/NodeGUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/GUI/NodeGUI.cpp.i
.PHONY : GUI/NodeGUI.cpp.i

GUI/NodeGUI.s: GUI/NodeGUI.cpp.s
.PHONY : GUI/NodeGUI.s

# target to generate assembly for a file
GUI/NodeGUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/GUI/NodeGUI.cpp.s
.PHONY : GUI/NodeGUI.cpp.s

GUI/RCWindow.o: GUI/RCWindow.cpp.o
.PHONY : GUI/RCWindow.o

# target to build an object file
GUI/RCWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/GUI/RCWindow.cpp.o
.PHONY : GUI/RCWindow.cpp.o

GUI/RCWindow.i: GUI/RCWindow.cpp.i
.PHONY : GUI/RCWindow.i

# target to preprocess a source file
GUI/RCWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/GUI/RCWindow.cpp.i
.PHONY : GUI/RCWindow.cpp.i

GUI/RCWindow.s: GUI/RCWindow.cpp.s
.PHONY : GUI/RCWindow.s

# target to generate assembly for a file
GUI/RCWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/GUI/RCWindow.cpp.s
.PHONY : GUI/RCWindow.cpp.s

GUI/main.o: GUI/main.cpp.o
.PHONY : GUI/main.o

# target to build an object file
GUI/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/GUI/main.cpp.o
.PHONY : GUI/main.cpp.o

GUI/main.i: GUI/main.cpp.i
.PHONY : GUI/main.i

# target to preprocess a source file
GUI/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/GUI/main.cpp.i
.PHONY : GUI/main.cpp.i

GUI/main.s: GUI/main.cpp.s
.PHONY : GUI/main.s

# target to generate assembly for a file
GUI/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RentACar.dir/build.make CMakeFiles/RentACar.dir/GUI/main.cpp.s
.PHONY : GUI/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RentACar"
	@echo "... Backtracking/Graph.o"
	@echo "... Backtracking/Graph.i"
	@echo "... Backtracking/Graph.s"
	@echo "... Backtracking/Node.o"
	@echo "... Backtracking/Node.i"
	@echo "... Backtracking/Node.s"
	@echo "... Backtracking/NodeLogistic.o"
	@echo "... Backtracking/NodeLogistic.i"
	@echo "... Backtracking/NodeLogistic.s"
	@echo "... GUI/ConnectionsGUI.o"
	@echo "... GUI/ConnectionsGUI.i"
	@echo "... GUI/ConnectionsGUI.s"
	@echo "... GUI/NodeGUI.o"
	@echo "... GUI/NodeGUI.i"
	@echo "... GUI/NodeGUI.s"
	@echo "... GUI/RCWindow.o"
	@echo "... GUI/RCWindow.i"
	@echo "... GUI/RCWindow.s"
	@echo "... GUI/main.o"
	@echo "... GUI/main.i"
	@echo "... GUI/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

